// <auto-generated />
namespace BAPA_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KursInfoVM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KursInfoVM));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111132499_KursInfoVM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
